# Generated by Django 5.0.7 on 2024-10-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date Created",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date Modified",
                        verbose_name="Date Modified",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Watchlist",
                "verbose_name_plural": "Watchlists",
            },
        ),
        migrations.CreateModel(
            name="WatchlistTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date Created",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date Modified",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_tickers",
                        to="tickers.ticker",
                        verbose_name="Ticker",
                    ),
                ),
                (
                    "watchlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_tickers",
                        to="watchlist.watchlist",
                        verbose_name="Watchlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist Ticker",
                "verbose_name_plural": "Watchlist Tickers",
                "unique_together": {("watchlist", "ticker")},
            },
        ),
        migrations.AddField(
            model_name="watchlist",
            name="tickers",
            field=models.ManyToManyField(
                related_name="watchlists",
                through="watchlist.WatchlistTicker",
                to="tickers.ticker",
                verbose_name="Tickers",
            ),
        ),
    ]
