# Generated by Django 5.0.6 on 2024-05-26 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickers", "0004_alter_ticker_name"),
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlist",
            options={"verbose_name": "Watchlist", "verbose_name_plural": "Watchlists"},
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="stocks",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="user",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date Created",
                verbose_name="Date Created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="watchlist",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="Date Modified", verbose_name="Date Modified"
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, verbose_name="Name"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="WatchlistTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date Created",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date Modified",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_tickers",
                        to="tickers.ticker",
                        verbose_name="Ticker",
                    ),
                ),
                (
                    "watchlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist_tickers",
                        to="watchlist.watchlist",
                        verbose_name="Watchlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Watchlist Ticker",
                "verbose_name_plural": "Watchlist Tickers",
                "unique_together": {("watchlist", "ticker")},
            },
        ),
        migrations.AddField(
            model_name="watchlist",
            name="tickers",
            field=models.ManyToManyField(
                related_name="watchlists",
                through="watchlist.WatchlistTicker",
                to="tickers.ticker",
                verbose_name="Tickers",
            ),
        ),
    ]
