# Generated by Django 5.0.6 on 2024-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Stock symbol",
                        max_length=10,
                        unique=True,
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Stock name",
                        max_length=100,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country",
                        max_length=50,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "ipo_year",
                    models.IntegerField(
                        blank=True,
                        help_text="IPO year",
                        null=True,
                        verbose_name="IPO Year",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="Sector",
                        max_length=50,
                        null=True,
                        verbose_name="Sector",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Industry",
                        max_length=50,
                        null=True,
                        verbose_name="Industry",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current Price",
                        max_digits=10,
                        null=True,
                        verbose_name="Current Price",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
