# Generated by Django 5.0.6 on 2024-05-26 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticker",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="ticker",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ticker",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="ticker",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date Created",
                verbose_name="Date Created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticker",
            name="date_modified",
            field=models.DateTimeField(
                auto_now=True, help_text="Date Modified", verbose_name="Date Modified"
            ),
        ),
    ]
