# Generated by Django 5.0.6 on 2024-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickers", "0002_remove_ticker_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="industry",
            field=models.CharField(
                blank=True,
                help_text="Industry",
                max_length=255,
                null=True,
                verbose_name="Industry",
            ),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="sector",
            field=models.CharField(
                blank=True,
                help_text="Sector",
                max_length=255,
                null=True,
                verbose_name="Sector",
            ),
        ),
    ]
