# Generated by Django 5.0.6 on 2024-05-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickers", "0003_alter_ticker_industry_alter_ticker_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Stock name",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
