# Generated by Django 5.1.2 on 2024-10-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_notification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last notification"
                    ),
                ),
                (
                    "notification_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Notification value",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("telegram", "Telegram"),
                            ("all", "All"),
                        ],
                        default="telegram",
                        max_length=10,
                        null=True,
                        verbose_name="Notification type",
                    ),
                ),
                (
                    "notification_criteria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("more_than", "More than"),
                            ("less_than", "Less than"),
                        ],
                        default="less_than",
                        max_length=10,
                        null=True,
                        verbose_name="Notification criteria",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tickers.ticker",
                        verbose_name="Ticker",
                    ),
                ),
            ],
        ),
    ]
