# Generated by Django 5.1.2 on 2024-10-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date Created",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date Modified",
                        verbose_name="Date Modified",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Stock symbol",
                        max_length=10,
                        unique=True,
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Stock name",
                        max_length=255,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country",
                        max_length=50,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "ipo_year",
                    models.IntegerField(
                        blank=True,
                        help_text="IPO year",
                        null=True,
                        verbose_name="IPO Year",
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        help_text="Sector",
                        max_length=255,
                        null=True,
                        verbose_name="Sector",
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="Industry",
                        max_length=255,
                        null=True,
                        verbose_name="Industry",
                    ),
                ),
                (
                    "last_sale",
                    models.CharField(
                        blank=True,
                        help_text="Last sale price",
                        max_length=50,
                        null=True,
                        verbose_name="Last Sale",
                    ),
                ),
                (
                    "net_change",
                    models.CharField(
                        blank=True,
                        help_text="Net change",
                        max_length=50,
                        null=True,
                        verbose_name="Net Change",
                    ),
                ),
                (
                    "percent_change",
                    models.CharField(
                        blank=True,
                        help_text="Percent change",
                        max_length=50,
                        null=True,
                        verbose_name="Percent Change",
                    ),
                ),
                (
                    "market_cap",
                    models.CharField(
                        blank=True,
                        help_text="Market capitalization",
                        max_length=50,
                        null=True,
                        verbose_name="Market Cap",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        help_text="Volume",
                        max_length=50,
                        null=True,
                        verbose_name="Volume",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
