# Generated by Django 5.1.2 on 2024-10-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticker",
            name="stock_exchange",
            field=models.CharField(
                blank=True,
                help_text="Stock exchange",
                max_length=255,
                null=True,
                verbose_name="Stock Exchange",
            ),
        ),
    ]
