# Generated by Django 5.1.2 on 2024-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickers", "0002_ticker_stock_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="symbol",
            field=models.CharField(
                help_text="Stock symbol",
                max_length=255,
                unique=True,
                verbose_name="Symbol",
            ),
        ),
    ]
