# Generated by Django 5.1.2 on 2024-10-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickers", "0003_alter_ticker_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticker",
            name="sector",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Sector",
                max_length=255,
                null=True,
                verbose_name="Sector",
            ),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="stock_exchange",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stock exchange",
                max_length=255,
                null=True,
                verbose_name="Stock Exchange",
            ),
        ),
        migrations.AlterField(
            model_name="ticker",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="Stock symbol",
                max_length=255,
                unique=True,
                verbose_name="Symbol",
            ),
        ),
    ]
