# Generated by Django 5.0.6 on 2024-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
